### ISSUE TITLE
[Bug] Incompatibility with Optifine's Dynamic Lights

### ISSUE THREAD

**Issue by gatoborrachon** [Meldexun/Nothirium#16]
**Describe the bug**
When you use Nothirium and Optifine (with the configuration of "Dynamic Lights" enabled) you won't get the expected effect of dynamic lights

**To Reproduce**
1. Enable the Dynamic Lights config options
2. Go to a dark place (or wait to the night)
3. Hold a torch in your hand

**Screenshots/Videos**
1.- With Nothirium
![2022-05-31_15 27 43](https://user-images.githubusercontent.com/61126174/171279330-10e3f500-5bc1-4a03-a640-0efe9e708c7c.png)

2.- Without Nothirium
![2022-05-31_15 30 46](https://user-images.githubusercontent.com/61126174/171279402-f3f8a227-8d17-458c-96fc-aa6986ac0cef.png)

**Versions**
Nothirium: 0.1.4-beta 
RenderLib: 1.0.7 
Forge: 14.23.5.2860
Minecraft: 1.12.2

Other mods (necessary to reproduce the bug): 
Optifine: 1.12.2_HD_U_G5

**Hardware**
CPU: Intel Core I3 3220
RAM: 8 GB (mixed brands, one was HyperX, don't know the exact model, sorry)
GPU: Radeon HD 7850
VRAM: 1GB

**Log File**
[latest.log](https://github.com/Meldexun/Nothirium/files/8809386/latest.log)
[debug.log](https://github.com/Meldexun/Nothirium/files/8809388/debug.log)

**Comment by mxnmnm** [comment]
Are there plans for this to get fixed or would that be too difficult to implement?

**Comment by xXDarkNovaXx** [comment]
I noticed that the dynamic light is on whether it is enabled in Optifine or not.
I don't know if this happens due to Nothirium or some other mod, but it works weird for me
The only difference Dynamic Light makes for me with Nothirium is whether the torch burns or not

Dynamic Light on:
![With Dynamic Light](https://user-images.githubusercontent.com/22129313/178171234-ede04ba7-6351-41f8-8d2e-d0574bec35d6.png)

Without Dynamic Light:
![Without Dynamic Light](https://user-images.githubusercontent.com/22129313/178171262-4c6646b3-ec53-4579-a9aa-7771dbc4f272.png)

**Comment by gatoborrachon** [comment]
oh, well, when we talk about Shaders, we can expect all kinds of strange behaviors, even without any other mod (for example, if you use certain shaders with AMD graphic cards)

**Comment by quentin452** [comment]
try the latest version of nothirium to watch if is fixed

**Comment by gatoborrachon** [comment]
sorry, forgot to say that 0.1.7 doesn't work too

**Comment by Gandalf360one** [comment]
Doesnt work with 0.1.8 too

**Comment by Meldexun** [comment]
Fixed in v1.12.2-0.2.0-beta
