### ISSUE TITLE
Incompatibility with Fluidlogged-Api

### ISSUE THREAD

**Issue by wed15** [Meldexun/Nothirium#27]
**Describe the bug**
When [Fluidlogged-Api](https://www.curseforge.com/minecraft/mc-mods/fluidlogged-api) and Nothirium installed together water and any kind of fluids are not visible on fluid-logged blocks. Reproduceable with only both mods.

**To Reproduce**
1. Install Fluidlogged-Api and Nothirium with dependency in same instance
2. Join any world
3. Waterlog any blocks and see if water is visible

**Screenshots**
Without Nothirium:
![2022-07-04_17 29 40](https://user-images.githubusercontent.com/86100898/177117873-59d65535-0e34-490e-b9ab-a1c91c6e83f2.png)
With Nothirium:
![2022-07-04_17 10 43](https://user-images.githubusercontent.com/86100898/177117886-044d4e9a-8ffa-409f-85d4-2ed4d2b4318e.png)

**Versions**
Nothirium: 0.1.6-beta
RenderLib: 1.1.0
Fluidlogged-Api: 1.8.1c

Forge: 14.23.5.2860
Minecraft: 1.12.2 (obviously)

**Hardware**
CPU: AMD Ryzen 5 3500 6-Core Processor
RAM: 16GB
GPU: Radeon RX 570 Series
VRAM: 4096MB

**Log File**
[latest.log](https://gist.github.com/wed15/d81619b713312754df9ab59a4896f4d8)
[debug.log](https://gist.github.com/wed15/a92e6e06285d9f64d4baff3a17347982)

**Comment by SlimeX300alt** [comment]
How  did the chunks loaded for you?

**Comment by jbredwards** [comment]
@Meldexun does implementing something similar to [`PluginRenderChunk`](https://github.com/CleanroomMC/Fluidlogged-API/blob/3667ee8636d76003ffa65530984073319d977d49/src/main/java/git/jbredwards/fluidlogged_api/mod/asm/plugins/vanilla/client/PluginRenderChunk.java) inside [`RenderChunkTaskCompile#run`](https://github.com/Meldexun/Nothirium/blob/f3bf470185bb8568eaca621c7f63e84f20143b0a/src/main/java/meldexun/nothirium/mc/renderer/chunk/RenderChunkTaskCompile.java#L62) fix the issue? Not gonna implement the fix from my end since it makes more sense to implement from your end (mine would require asm, yours doesn't).

**Comment by Meldexun** [comment]
@jbredwards I guess that would fix the incompatibility. But I don't use the vanilla classes like `ChunkCompileTaskGenerator` or `CompiledChunk`. Thus I would have to copy all three `ASMHooks#renderChunk` methods which isn't something I want to maintain.

**Comment by Meldexun** [comment]
Fixed through #41
